### ISSUE TITLE
Folders are not getting proper ownership permissions on move

### ISSUE THREAD

**Issue by tamburra** [monstermuffin/mergerfs-cache-mover#1]
Folders that are moved over are getting root user ownership instead of the desired user if the folder is not already existing in the pool when moved from cache drive.  Files are getting the correct user ownership based on the configuration file, folders are not.

For example.
Cache drive has "Folder A" with permissions "user1:group1".
Folder does not exist in the pool drive.
Run script as root.
"Folder A" is now in the pool drive with permissions "root:group1"
I would have to run this script as "user1" in order to get the proper permissions on new folders.

This only seems to happen with folders that don't already exist in the pool drive.

**Comment by monstermuffin** [comment]
@tamburra I have noticed this too actually but have been manually fixing it, I didn't realise it was the script causing it. 

I have modified the rsync command so that it now should set directory permissions, see: afa54f21432b128514a0d3fb6aedd24b2fbb962d

Can you please update the script and let me know if this fixed it for you?

**Comment by monstermuffin** [comment]
Turns out I didn't fix it in that last commit but I've tested now and it looks better. Can you please let me know @tamburra? Commit is here: 061091c97bf3442b02a059dd4c5681db2006284a

FYI: You will need new config options `FILE_CHMOD` and `DIR_CHMOD`. These are in the example config and updated in the readme.

**Comment by monstermuffin** [comment]
Closing this, let me know if there are still issues, it's been working well for me.

**Comment by hendrikbl** [comment]
This still seems to be an issue. It looks like this line is responsible for creating the new directories.

https://github.com/monstermuffin/mergerfs-cache-mover/blob/72796fe9f3f5500212fde7053b39d25dbf4623ec/cache-mover.py#L218

But the only call to chown happens when setting the file permissions, not the destination folders.

https://github.com/monstermuffin/mergerfs-cache-mover/blob/72796fe9f3f5500212fde7053b39d25dbf4623ec/cache-mover.py#L226

Maybe you missed it when switching from rsync?
